"""Qualification inputs bound to product truth records, never caller-authored booleans."""

from __future__ import annotations

from datetime import datetime
from typing import Literal

from pydantic import Field, model_validator
from traincapsule_core.base import ProductModel, digest_json
from traincapsule_core.models import (
    Digest,
    EnvironmentIdentity,
    EvidenceArtifact,
    EvidenceCompletenessReport,
    ExperimentEconomics,
    FindingAttribution,
    Identifier,
    IncidentCase,
    NativeFinding,
    WorkloadIdentity,
)

NATIVE_BASELINE_POLICY = "traincapsule-native-baseline-v1"
NATIVE_DECISION_POLICY = "traincapsule-native-sufficiency-v1"
NATIVE_SUFFICIENT_DECISION = (
    "Native evidence is sufficient to block the candidate: collective lifecycle states disagree."
)


class NativeBaseline(ProductModel):
    schema_version: int = Field(default=1, ge=1, le=1)
    case_id: Identifier
    workload_id: Digest
    baseline_environment_id: Digest
    candidate_environment_id: Digest
    generation_policy_version: Literal["traincapsule-native-baseline-v1"] = NATIVE_BASELINE_POLICY
    tool_name: str = Field(min_length=1)
    tool_version: str = Field(min_length=1)
    source_format: str = Field(min_length=1)
    source_format_version: str = Field(min_length=1)
    import_digest: Digest
    command: list[str] = Field(min_length=1)
    configuration: dict[str, object]
    artifacts: list[EvidenceArtifact] = Field(min_length=1)
    binding_artifacts: list[EvidenceArtifact] = Field(min_length=2)
    findings: list[NativeFinding] = Field(min_length=1)
    limitations: list[str] = Field(min_length=1)
    import_warnings: list[str]
    missing_ranks: list[int]
    elapsed_seconds: int = Field(ge=0)
    operator_effort_seconds: int = Field(ge=0)
    decision_reached: str | None = None
    decision_policy_version: Literal["traincapsule-native-sufficiency-v1"] = NATIVE_DECISION_POLICY
    decision_evidence_refs: list[Digest]
    decision_provenance_digest: Digest | None = None
    unresolved_questions: list[str]
    executed_at: datetime

    @model_validator(mode="after")
    def native_attribution_and_case_binding(self) -> NativeBaseline:
        artifact_ids = {artifact.artifact_id for artifact in self.artifacts}
        if any(artifact.case_id != self.case_id for artifact in self.artifacts):
            raise ValueError("native baseline contains cross-case artifacts")
        expected_binding = (
            self.workload_id,
            self.baseline_environment_id,
            self.candidate_environment_id,
        )
        if any(
            (
                artifact.workload_id,
                artifact.baseline_environment_id,
                artifact.candidate_environment_id,
            )
            != expected_binding
            for artifact in self.artifacts
        ):
            raise ValueError("native baseline artifacts are not identity-bound")
        if any(
            artifact.case_id != self.case_id
            or (
                artifact.workload_id,
                artifact.baseline_environment_id,
                artifact.candidate_environment_id,
            )
            != expected_binding
            for artifact in self.binding_artifacts
        ):
            raise ValueError("native binding artifacts are not identity-bound")
        for finding in self.findings:
            if finding.attribution is not FindingAttribution.NATIVE_TOOL_FOUND:
                raise ValueError("native baseline findings must be attributed NATIVE_TOOL_FOUND")
            if not set(finding.evidence_refs) <= artifact_ids:
                raise ValueError("native finding references an artifact outside its baseline")
        if self.decision_reached is None:
            if not self.unresolved_questions:
                raise ValueError("unresolved native baseline requires unresolvedQuestions")
            if self.decision_evidence_refs or self.decision_provenance_digest is not None:
                raise ValueError("unreached native decision cannot carry decision provenance")
        else:
            if self.decision_reached != NATIVE_SUFFICIENT_DECISION:
                raise ValueError("native decision must be generated by the supported policy")
            if (
                not self.decision_evidence_refs
                or not set(self.decision_evidence_refs) <= artifact_ids
            ):
                raise ValueError("native decision requires bound baseline evidence")
            expected = digest_json(
                {
                    "caseId": self.case_id,
                    "decision": self.decision_reached,
                    "evidenceRefs": sorted(self.decision_evidence_refs),
                    "policyVersion": self.decision_policy_version,
                }
            )
            if self.decision_provenance_digest != expected:
                raise ValueError("native decision provenance digest does not match")
        return self


class PreflightInputs(ProductModel):
    schema_version: int = Field(default=1, ge=1, le=1)
    evaluated_at: datetime
    incident_case: IncidentCase
    workload_identity: WorkloadIdentity
    baseline_environment: EnvironmentIdentity
    candidate_environment: EnvironmentIdentity
    verified_artifacts: list[EvidenceArtifact] = Field(min_length=1)
    completeness_report: EvidenceCompletenessReport
    native_baseline: NativeBaseline
    original_experiment_economics: ExperimentEconomics
    proposed_experiment_economics: ExperimentEconomics

    @model_validator(mode="after")
    def all_records_are_case_and_identity_bound(self) -> PreflightInputs:
        case = self.incident_case
        if self.evaluated_at.tzinfo is None or case.decision_deadline.tzinfo is None:
            raise ValueError("preflight timestamps must carry timezone offsets")
        if case.workload_id != self.workload_identity.workload_id:
            raise ValueError("case workloadId does not match workload identity")
        if case.baseline_environment_id != self.baseline_environment.environment_id:
            raise ValueError("case baselineEnvironmentId does not match baseline identity")
        if case.candidate_environment_id != self.candidate_environment.environment_id:
            raise ValueError("case candidateEnvironmentId does not match candidate identity")
        if self.completeness_report.case_id != case.case_id:
            raise ValueError("completeness report belongs to a different case")
        if self.native_baseline.case_id != case.case_id:
            raise ValueError("native baseline belongs to a different case")
        expected_binding = (
            self.workload_identity.workload_id,
            self.baseline_environment.environment_id,
            self.candidate_environment.environment_id,
        )
        if (
            self.native_baseline.workload_id,
            self.native_baseline.baseline_environment_id,
            self.native_baseline.candidate_environment_id,
        ) != expected_binding:
            raise ValueError("native baseline does not match preflight identities")
        artifacts = {artifact.artifact_id: artifact for artifact in self.verified_artifacts}
        if any(artifact.case_id != case.case_id for artifact in artifacts.values()):
            raise ValueError("verifiedArtifacts contains cross-case evidence")
        if any(
            (
                artifact.workload_id,
                artifact.baseline_environment_id,
                artifact.candidate_environment_id,
            )
            != expected_binding
            for artifact in artifacts.values()
        ):
            raise ValueError("verifiedArtifacts are not bound to preflight identities")
        if not set(case.evidence_refs) <= artifacts.keys():
            raise ValueError("case evidenceRefs are not all verified")
        for requirement in self.completeness_report.requirements:
            if not set(requirement.artifact_refs) <= artifacts.keys():
                raise ValueError("completeness report references unverified evidence")
        if (
            not {artifact.artifact_id for artifact in self.native_baseline.artifacts}
            <= artifacts.keys()
        ):
            raise ValueError("native baseline artifacts are not all verified")
        if (
            not {artifact.artifact_id for artifact in self.native_baseline.binding_artifacts}
            <= artifacts.keys()
        ):
            raise ValueError("native binding artifacts are not all verified")
        return self
