"""Exact controlled vocabularies for the TrainCapsule V3 factory."""

from enum import StrEnum


class Lane(StrEnum):
    PRODUCT = "PRODUCT"
    MARKET = "MARKET"
    COMPETITOR = "COMPETITOR"
    TRUST = "TRUST"
    FACTORY = "FACTORY"


class WorkKind(StrEnum):
    CODE = "CODE"
    SPECIFICATION = "SPECIFICATION"
    RESEARCH = "RESEARCH"
    CONTROLLED_EXPERIMENT = "CONTROLLED_EXPERIMENT"
    EXTERNAL_EVIDENCE = "EXTERNAL_EVIDENCE"
    HUMAN_REVIEW = "HUMAN_REVIEW"
    COMMERCIAL_EXPERIMENT = "COMMERCIAL_EXPERIMENT"
    MAINTENANCE = "MAINTENANCE"
    MIGRATION = "MIGRATION"


class WorkStatus(StrEnum):
    PROPOSED = "PROPOSED"
    READY = "READY"
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    PAUSED_QUOTA = "PAUSED_QUOTA"
    WAITING_EXTERNAL = "WAITING_EXTERNAL"
    WAITING_HUMAN = "WAITING_HUMAN"
    BLOCKED_TECHNICAL = "BLOCKED_TECHNICAL"
    BLOCKED_POLICY = "BLOCKED_POLICY"
    PASSED_ENGINEERING = "PASSED_ENGINEERING"
    REJECTED_VALUE = "REJECTED_VALUE"
    NATIVE_SUFFICIENT = "NATIVE_SUFFICIENT"
    DEFERRED = "DEFERRED"
    SUPERSEDED = "SUPERSEDED"
    CANCELLED = "CANCELLED"
    COMPLETED = "COMPLETED"


class Disposition(StrEnum):
    KEEP = "KEEP"
    INTEGRATE_EXISTING_BACKEND = "INTEGRATE_EXISTING_BACKEND"
    UPSTREAM = "UPSTREAM"
    NARROW = "NARROW"
    REPLACE = "REPLACE"
    PAUSE = "PAUSE"
    STOP = "STOP"
    NOT_REVIEWED = "NOT_REVIEWED"


class OwnerType(StrEnum):
    AI = "AI"
    FOUNDER = "FOUNDER"
    HUMAN_REVIEWER = "HUMAN_REVIEWER"
    CUSTOMER = "CUSTOMER"
    EXTERNAL_PARTY = "EXTERNAL_PARTY"


class RiskTier(StrEnum):
    MECHANICAL = "MECHANICAL"
    STANDARD = "STANDARD"
    INTEGRATION = "INTEGRATION"
    TRUST_CORE = "TRUST_CORE"
    EXTERNAL = "EXTERNAL"


class EngineeringMaturity(StrEnum):
    DESIGN_ONLY = "DESIGN_ONLY"
    IMPLEMENTED_EXPERIMENTAL = "IMPLEMENTED_EXPERIMENTAL"
    CONTROLLED_VALIDATED = "CONTROLLED_VALIDATED"
    EXTERNAL_VALIDATED = "EXTERNAL_VALIDATED"
    DEPRECATED = "DEPRECATED"


class CommercialMaturity(StrEnum):
    NOT_EVALUATED = "NOT_EVALUATED"
    NATIVE_ADVANTAGE_UNPROVEN = "NATIVE_ADVANTAGE_UNPROVEN"
    NATIVE_ADVANTAGE_DEMONSTRATED = "NATIVE_ADVANTAGE_DEMONSTRATED"
    EXTERNAL_VALUE_DEMONSTRATED = "EXTERNAL_VALUE_DEMONSTRATED"
    COMMERCIALLY_SUPPORTED = "COMMERCIALLY_SUPPORTED"
    WITHDRAWN = "WITHDRAWN"


class MilestoneType(StrEnum):
    TRUST = "TRUST"
    ENGINEERING = "ENGINEERING"
    COMMERCIAL = "COMMERCIAL"


class MilestoneStatus(StrEnum):
    PROPOSED = "PROPOSED"
    ACTIVE = "ACTIVE"
    WAITING_EXTERNAL = "WAITING_EXTERNAL"
    WAITING_HUMAN = "WAITING_HUMAN"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class EvidenceType(StrEnum):
    CUSTOMER_CONVERSATION = "CUSTOMER_CONVERSATION"
    INCIDENT_ARCHIVE_ACCESS = "INCIDENT_ARCHIVE_ACCESS"
    PAID_PREFLIGHT = "PAID_PREFLIGHT"
    PAID_PILOT = "PAID_PILOT"
    DECISION_CHANGED = "DECISION_CHANGED"
    SECOND_PAID_ACTION = "SECOND_PAID_ACTION"
    INDEPENDENT_OPERATOR = "INDEPENDENT_OPERATOR"
    HUMAN_REVIEW = "HUMAN_REVIEW"
    UPSTREAM_ACCEPTANCE = "UPSTREAM_ACCEPTANCE"
    PROVIDER_ACCEPTANCE = "PROVIDER_ACCEPTANCE"


class ArtifactLocationClass(StrEnum):
    TRUSTED_EXTERNAL = "TRUSTED_EXTERNAL"
    CUSTOMER_LOCAL = "CUSTOMER_LOCAL"
    REDACTED_REFERENCE = "REDACTED_REFERENCE"


class SignatureAlgorithm(StrEnum):
    ED25519 = "ed25519"
    EXTERNAL_TRUSTED_ROOT = "external-trusted-root"


class ApprovalScope(StrEnum):
    SOURCE_OF_TRUTH_MIGRATION = "SOURCE_OF_TRUTH_MIGRATION"
    EXTERNAL_RELEASE = "EXTERNAL_RELEASE"
    COMMERCIAL_PACK_RELEASE = "COMMERCIAL_PACK_RELEASE"
    TRUST_CORE_CHANGE = "TRUST_CORE_CHANGE"
    SECURITY_BOUNDARY_CHANGE = "SECURITY_BOUNDARY_CHANGE"
    CUSTOMER_CLAIM = "CUSTOMER_CLAIM"
    ROADMAP_EXPANSION = "ROADMAP_EXPANSION"
    WEDGE_DECISION = "WEDGE_DECISION"


class ApprovalDecision(StrEnum):
    APPROVED = "APPROVED"
    APPROVED_WITH_CONDITIONS = "APPROVED_WITH_CONDITIONS"
    REJECTED = "REJECTED"


class ReleaseDecision(StrEnum):
    NOT_EVALUATED = "NOT_EVALUATED"
    HOLD = "HOLD"
    DRAFT_PULL_REQUEST = "DRAFT_PULL_REQUEST"
    APPROVED_FOR_MERGE = "APPROVED_FOR_MERGE"
    REJECTED = "REJECTED"
